version: '3.8'

services:
  wgtorrent:
    image: wgtorrent
    container_name: wgtorrent
    cap_add:
      - NET_ADMIN
    volumes:
      - /zfs:/zfs
      - /home/daedr/docker/wgtorrent/config/rtorrent:/rtorrent
      - /zfs/mnt/torrents:/torrents
      - /home/daedr/docker/wgtorrent/config/wireguard:/wireguard
      - /run/resolvconf/resolv.conf:/etc/resolv.conf
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    stdin_open: true
    tty: true
